// Code generated by MockGen. DO NOT EDIT.
// Source: internal/server/services/metrics.go

// Package internal/server/repository/mock is a generated GoMock package.
package internal

import (
	"github.com/golang/mock/gomock"
	"github.com/lenarsaitov/metrics-tpl/internal/server/models"
	"reflect"
)

// MockStorage is a mock of Storage interface.
type MockStorage struct {
	ctrl     *gomock.Controller
	recorder *MockStorageMockRecorder
}

// MockStorageMockRecorder is the mock recorder for MockStorage.
type MockStorageMockRecorder struct {
	mock *MockStorage
}

// NewMockStorage creates a new mock instance.
func NewMockStorage(ctrl *gomock.Controller) *MockStorage {
	mock := &MockStorage{ctrl: ctrl}
	mock.recorder = &MockStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStorage) EXPECT() *MockStorageMockRecorder {
	return m.recorder
}

// AddCounter mocks base method.
func (m *MockStorage) AddCounter(name string, value int64) int64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddCounter", name, value)
	ret0, _ := ret[0].(int64)
	return ret0
}

// AddCounter indicates an expected call of AddCounter.
func (mr *MockStorageMockRecorder) AddCounter(name, value interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddCounter", reflect.TypeOf((*MockStorage)(nil).AddCounter), name, value)
}

// GetAll mocks base method.
func (m *MockStorage) GetAll() models.Metrics {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll")
	ret0, _ := ret[0].(models.Metrics)
	return ret0
}

// GetAll indicates an expected call of GetAll.
func (mr *MockStorageMockRecorder) GetAll() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockStorage)(nil).GetAll))
}

// GetCounterMetric mocks base method.
func (m *MockStorage) GetCounterMetric(name string) *int64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCounterMetric", name)
	ret0, _ := ret[0].(*int64)
	return ret0
}

// GetCounterMetric indicates an expected call of GetCounterMetric.
func (mr *MockStorageMockRecorder) GetCounterMetric(name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCounterMetric", reflect.TypeOf((*MockStorage)(nil).GetCounterMetric), name)
}

// GetGaugeMetric mocks base method.
func (m *MockStorage) GetGaugeMetric(name string) *float64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGaugeMetric", name)
	ret0, _ := ret[0].(*float64)
	return ret0
}

// GetGaugeMetric indicates an expected call of GetGaugeMetric.
func (mr *MockStorageMockRecorder) GetGaugeMetric(name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGaugeMetric", reflect.TypeOf((*MockStorage)(nil).GetGaugeMetric), name)
}

// ReplaceGauge mocks base method.
func (m *MockStorage) ReplaceGauge(name string, value float64) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ReplaceGauge", name, value)
}

// ReplaceGauge indicates an expected call of ReplaceGauge.
func (mr *MockStorageMockRecorder) ReplaceGauge(name, value interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReplaceGauge", reflect.TypeOf((*MockStorage)(nil).ReplaceGauge), name, value)
}
